name: Keep Render App Awake

on:
  #schedule:
    #- cron: "*/3 * * * *"  # every 10 minutes (UTC)
  workflow_dispatch:        # optional manual trigger from GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render /health endpoint
        run: |
          echo "🔁 Pinging https://github-pr-watcher.onrender.com/health ..."
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://github-pr-watcher.onrender.com/health)

          if [ "$STATUS_CODE" -eq 200 ]; then
            echo "✅ Render app is awake and healthy."
          else
            echo "❌ Failed to ping. Status: $STATUS_CODE"
            exit 1
          fi
